[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
RegistryInstances = "2792f1a3-b283-48e8-9a74-f99dce5104f3"
TidierFiles = "8ae5e7a9-bdd3-4c93-9cc3-9df4d5d947db"

[compat]
DataFrames = "1"
LibPQ = "1"
RegistryInstances = "0.1"
TidierFiles = "0.3.2"
